<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>DevendraTest</groupId>
  <artifactId>SeleniumFrameworkDesign1</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>SeleniumFrameworkDesign1</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- 183 added as it was not there  -->
    <maven.compiler.source>25</maven.compiler.source>
     <maven.compiler.target>25</maven.compiler.target>  
  </properties>
  <!-- Maven Usage plugin -->
    <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.5.5</version>
           <!-- Maven Usage plugin to use testng-->
          <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>testng.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>        
        </plugin>
           <!-- session 184 ADDED FOR Using Suite XML Files-->
       <!--  <plugin>  not required as profiles are addedd
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.3.1</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>testSuites/testng.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin> -->
      
      </plugins>
    </pluginManagement>
  </build>
  
  <profiles>   <!-- profiles are added to run-->
   	<profile> <!-- regression in which added testng xml-->
  	<id> Regression</id>

  	 <build>
    <pluginManagement>
      <plugins>
        <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.3.1</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>testSuites/testng.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin>
        </plugins>
    </pluginManagement>
  </build>
    	</profile>
  	
  	   	<profile>   <!-- testng2 in which added testng2 xml-->
  	<id> testng2</id>
  	
  	  	 <build>
    <pluginManagement>
      <plugins>
        <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.3.1</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>testSuites/testng2.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin>
        </plugins>
    </pluginManagement>
  </build>
  	
  	</profile>
  	
  	   	<profile> <!-- Errorvalidation in which added Errorvalidation xml-->
  	<id>Error</id>
  	  	 <build>
    <pluginManagement>
      <plugins>
        <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.3.1</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>testSuites/ErrorValidationTests22.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin>
        </plugins>
    </pluginManagement>
  </build>
  	
  	</profile>
  	
  	   	<profile> <!-- Purchase in which addedpurchase  xml-->
  	<id> Purchase</id>

  	  	 <build>
    <pluginManagement>
      <plugins>
        <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.3.1</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>testSuites/Purchase21_177.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin>
        </plugins>
    </pluginManagement>
  </build>
  
    	</profile>
    	
    	<profile> <!-- Cucumber  session 200-->
  	<id>CucumberTests</id>

  	 <build>
    <pluginManagement>
      <plugins>
        <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.3.1</version>
        <configuration>
          <includes>
            <include>**/TestNGTestRunner_23.java</include>        <!-- includes will use in cucumber and it will pick TestNGTestRunner_23 file from any location to tun-->         
          </includes>
        </configuration>
      </plugin>
        </plugins>
    </pluginManagement>
  </build>
    	</profile>
  </profiles>
  

  <dependencies>

<!-- Source: https://mvnrepository.com/artifact/io.github.bonigarcia/webdrivermanager 6.3.3 -->
<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>6.3.4</version>
    <scope>compile</scope>
</dependency>


  	<!--<dependency>
  		<groupId>Introduction</groupId>
  		<artifactId>selenium-java</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  	</dependency>-->
  	
<!-- Source: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java 4.43-->
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.45.0</version>
    <scope>compile</scope>
</dependency>
  	
<!-- Source: https://mvnrepository.com/artifact/org.testng/testng -->
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.12.0</version>
    <scope>test</scope>
</dependency>

<!-- Source: https://mvnrepository.com/artifact/io.cucumber/cucumber-java ses 196-->
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>7.34.6</version>
    <scope>compile</scope>
</dependency>

<!-- Source: https://mvnrepository.com/artifact/io.cucumber/cucumber-testng sess 196-->
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-testng</artifactId>
    <version>7.34.6</version>
    <scope>compile</scope>
</dependency>

<!-- Source: https://mvnrepository.com/artifact/com.aventstack/extentreports session 180-->
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>5.1.2</version>
    <scope>compile</scope>
</dependency>


<!-- added for  No SLF4J providers were found. session 170 -->
<dependency>
  <groupId>ch.qos.logback</groupId>
  <artifactId>logback-classic</artifactId>
  <version>1.5.6</version>
</dependency>

<!-- Source: https://mvnrepository.com/artifact/tools.jackson.core/jackson-databind session 21-177-->
<dependency>
    <groupId>tools.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>3.2.1</version>
    <scope>compile</scope>
</dependency>

<!--
  	<dependency>
  		<groupId>DevendraTestMaven_22</groupId>
  		<artifactId>ExtentReports_22</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  	</dependency>
  	-->
  	
  </dependencies>
</project>
